/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdaptersRouteImport } from './routes/adapters'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as HallRouteImport } from './routes/hall'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as RRouteImport } from './routes/r'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptersRoute = AdaptersRouteImport.update({
  id: '/adapters',
  path: '/adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const HallRoute = HallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoute = RRouteImport.update({
  id: '/r',
  path: '/r',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/batch': typeof BatchRoute
  '/dossier': typeof DossierRoute
  '/hall': typeof HallRoute
  '/offline': typeof OfflineRoute
  '/r': typeof RRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/batch': typeof BatchRoute
  '/dossier': typeof DossierRoute
  '/hall': typeof HallRoute
  '/offline': typeof OfflineRoute
  '/r': typeof RRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adapters': typeof AdaptersRoute
  '/batch': typeof BatchRoute
  '/dossier': typeof DossierRoute
  '/hall': typeof HallRoute
  '/offline': typeof OfflineRoute
  '/r': typeof RRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/adapters' | '/batch' | '/dossier' | '/hall' | '/offline' | '/r'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/adapters' | '/batch' | '/dossier' | '/hall' | '/offline' | '/r'
  id:
    | '__root__'
    | '/'
    | '/adapters'
    | '/batch'
    | '/dossier'
    | '/hall'
    | '/offline'
    | '/r'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptersRoute: typeof AdaptersRoute
  BatchRoute: typeof BatchRoute
  DossierRoute: typeof DossierRoute
  HallRoute: typeof HallRoute
  OfflineRoute: typeof OfflineRoute
  RRoute: typeof RRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adapters': {
      id: '/adapters'
      path: '/adapters'
      fullPath: '/adapters'
      preLoaderRoute: typeof AdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall': {
      id: '/hall'
      path: '/hall'
      fullPath: '/hall'
      preLoaderRoute: typeof HallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r': {
      id: '/r'
      path: '/r'
      fullPath: '/r'
      preLoaderRoute: typeof RRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptersRoute: AdaptersRoute,
  BatchRoute: BatchRoute,
  DossierRoute: DossierRoute,
  HallRoute: HallRoute,
  OfflineRoute: OfflineRoute,
  RRoute: RRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
